### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by sysdef** [wblondel/PagesJaunes-Scraper#12]
Please provide the text in English, too. That will make the solution usable for the rest of the world.

**Comment by wblondel** [comment]
Hi!

You're right! I have not taken a look at this project for a long time, I don't even know if it still works. SoLocal (owner of the French Yellow pages) is deleting more and more online PDF directories so I'll have to check which ones can still be downloaded and which ones can't.

I'll take some time this evening to check this and to add an English translation.

**Comment by wblondel** [comment]
Hi there!

I re-wrote the program, it is now better and is behaving smarter than before:
- when selecting a department, the tool shows which phone books are available by checking a database I created (phonebooks.sqlite). If the phone book you selected isn't available anymore on the PagesJaunes server, it updates the local database so that the program doesn't list this phone book anymore.
- localization ;) English translation is available.
- no more fancy progress bars, because it is useless. so no more tqdm and colorama dependencies.
- it now downloads ALL pages of a phone book, including cover pages.
- if a file already exists on disk, it doesn't download it again. useful if you want to resume a crashed download
